services:
  mtr-frontend:
    build:
      context: .
      dockerfile: mtr-frontend/frontend.Dockerfile
    image: mtr-frontend:latest
    container_name: mtr-frontend
    depends_on:
      - mtr-backend
    volumes:
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "8443:443"        # только HTTPS наружу
    networks:
      - mtr-net
    restart: unless-stopped

  mtr-backend:
    build:
      context: .
      dockerfile: mtr-backend/backend.Dockerfile
    image: mtr-backend:latest
    container_name: mtr-backend
    # ПОДКЛЮЧАЕМ 2 env-файла: сначала локальный .env (jwt/прочее), затем .env.db (БД-переменные)
    env_file:
      - mtr-backend/.env
      - ./.env.db
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    networks:
      - mtr-net
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: mtr-postgres
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - mtr-net
    restart: unless-stopped

networks:
  mtr-net:
    driver: bridge
